name: habitify2

type: rails

up:
  - homebrew:
    - openssl
    - shopify/shopify/mysql-client:
        or:        [mysql]
        conflicts: [mysql-connector-c]
    # - another_package
  - ruby: 2.5.1
  - bundler
  - railgun
  - database:
      bootstrap: bin/rails db:create db:schema:load
      migrate: bin/rails db:migrate db:test:prepare
      host: habitify2.railgun
      user: root
      password: ''
      database: habitify2_development

server:
  port: 26819

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run:    bin/rails test

# These use fuzzy-matching, so you can (e.g.) `dev open app`
open:
  "My Application": https://habitify2.myshopify.io
